# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'XMPPFileTransfer' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XMPPFileTransfer
pod 'XMPPFramework', :git => "https://github.com/robbiehanson/XMPPFramework.git", :branch => 'master'
pod 'KissXML/SwiftNSXML', :git => "https://github.com/robbiehanson/KissXML.git", :branch => 'master'
end
